name: "Opspresso Builder"
description: "Builder for GitHub Action"
author: "Jungyoul Yu <@nalbam>"

branding:
  icon: "box"
  color: "blue"

runs:
  using: docker
  image: docker://opspresso/action-builder:v0.7.5
